# Generated by Django 4.0.2 on 2022-02-04 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_card', to='main.product', verbose_name='product_name'),
        ),
    ]
